### ISSUE TITLE
Fatal error re libphonenumber/PhoneNumberUtil.php upon enabling on 5.2.x

### ISSUE THREAD

**Issue by petednz** [cividesk/com.cividesk.normalize#11]
Just reporting that I got this when testing this extension on 5.2.x

`Fatal error: require_once(): Failed opening required 'libphonenumber/PhoneNumberUtil.php' (include_path='/srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/extensions/com.cividesk.normalize/:/srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/extensions/nz.co.fuzion.civitoken/:/srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/extensions/uk.co.vedaconsulting.mosaico/:/srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/extensions/org.civicrm.flexmailer/:/srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/extensions/org.civicrm.shoreditch/:/srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/extensions/nz.co.fuzion.civixero/:/srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/extensions/nz.co.fuzion.accountsync/:/srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/extensions/nz.co.fuzion.fmcmembership/:/srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/extensions/nz.co.fuzion.transactional/:/srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/extensions/nz.co.fuzion.omnipaymultiprocessor/vendor/phpunit/phpunit-mock-objects:/srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/ext in /srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/extensions/com.cividesk.normalize/CRM/Utils/Normalize.php on line 25 `

**Comment by petednz** [comment]
And thereafter I get 

Warning: require_once(libphonenumber/PhoneNumberUtil.php): failed to open stream: No such file or directory in require_once() (line 25 of /srv/www/fmc/fmc.fudev.co.nz/sites/all/civicrm/extensions/com.cividesk.normalize/CRM/Utils/Normalize.php).

sites/all/civicrm/extensions/com.cividesk.normalize/packages/libphonenumber/PhoneNumberUtil.php

does exist at that path

**Comment by nganivet** [comment]
@petednz Seems like it is not finding the includes. We alter the path in function function normalize_civicrm_config(&$config), maybe you can add some traces there to see what is happening.

**Comment by nganivet** [comment]
@mlutfy Thanks for the report. @petednz Have you been able to resolve this? If so, can you provide a PR? Thanks.

**Comment by nganivet** [comment]
Closed as non-reproducible.

**Comment by andyburnsco** [comment]
Received same error (https://github.com/cividesk/com.cividesk.normalize/issues/11#issue-333442181) when trying to update to from version 1.0 to 1.1 on Civi 5.24.4

`Fatal error: require_once(): Failed opening required 'libphonenumber/PhoneNumberUtil.php' (include_path='/wp-content/uploads/civicrm/ext/com.cividesk.normalize/:/wp-content/uploads/civicrm/ext/minifier/:/wp-content/uploads/civicrm/ext/org.civicoop.emailapi/:/wp-content/uploads/civicrm/ext/com.joineryhq.profcond/:/wp-content/uploads/civicrm/ext/firewall/:/wp-content/uploads/civicrm/ext/stripe-5.4.1/:/wp-content/uploads/civicrm/ext/com.iatspayments.civicrm/:/wp-content/uploads/civicrm/ext/custompermissions/:/wp-content/uploads/civicrm/ext/com.aghstrategies.eventmembershipsignup/:/wp-content/uploads/civicrm/ext/org.civicrm.profileimageurl/:/wp-content/uploads/civicrm/ext/mjwshared/:/wp-content/uploads/civicrm/ext/nz.co.fuzion.relatedpermissions/:/wp-content/uploads/civicrm/ext/org.civicrm.contactlayout/:/wp-content/uploads/civicrm/e in /wp-content/uploads/civicrm/ext/com.cividesk.normalize/CRM/Utils/Normalize.php on line 25`
