### ISSUE TITLE
4.6 version?

### ISSUE THREAD

**Issue by JoeMurray** [cividesk/com.cividesk.normalize#2]
I have a client who would like to upgrade from 4.4 to 4.6 and is using this extension.

What tasks would be needed to do a 4.6 version off the top of your head? Is it likely to be quite simple? Do you have a timeframe when you are intending to release a 4.6 compatible version?

**Comment by nganivet** [comment]
Joe – can you try just adding 4.6 in the info.xml? The hooks have not changed, so it should work out of the box.

**Comment by nganivet** [comment]
Sorry it took so long, closed.
