### ISSUE TITLE
Apostrophe s is capitalized when followed by another word

### ISSUE THREAD

**Issue by mjwright** [cividesk/com.cividesk.normalize#5]
An organization name like "joe's diner" becomes "Joe'S Diner".  It works properly without the second word (e.g., "joe's" becomes "Joe's").

**Comment by mlutfy** [comment]
This happens only when using `’` (ex: when copy-pasting from MS Word with smart-quotes, automatically converting to typographic-apostrophe), not `'` (the key on the keyboard, aka typewriter apostrophe).

My fix was to do an `str_replace` to convert those apostrophes to the plain typewriter apostrophe.

I'm playing around with the code, and so far, this seems to be working best for me:

```
// Test case: Joe’s diner -> Joe’s Diner
// Test case: MONTRÉAL // Montréal
$addressValue = str_replace("’", "'", $addressValue);
$address[$name] = mb_convert_case(mb_strtolower($addressValue), MB_CASE_TITLE, "UTF-8");
```

https://en.wikipedia.org/wiki/Apostrophe#Smart_quotes

**Comment by mlutfy** [comment]
@nganivet https://github.com/cividesk/com.cividesk.normalize/pull/12

**Comment by nganivet** [comment]
Fixed by mlufty's PR.
