### ISSUE TITLE
PHP warnings when saving the configuration form

### ISSUE THREAD

**Issue by jmcclelland** [cividesk/com.cividesk.normalize#6]
Notice: Undefined property: CRM_Admin_Form_Setting_Normalize::$_values in CRM_Admin_Form_Setting_Normalize->buildQuickForm() (line 92 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).
    Strict warning: Only variables should be passed by reference in CRM_Admin_Form_Setting_Normalize->postProcess() (line 175 of /var/www/powerbase/sites/all/extensions/normalize/CRM/Admin/Form/Setting/Normalize.php).

**Comment by nganivet** [comment]
Thanks Jamie, merged.
