### ISSUE TITLE
add exceptions for street address directionals (NW, E, S, SW, etc)

### ISSUE THREAD

**Issue by Stoob** [cividesk/com.cividesk.normalize#8]
TwoMice and I will be adding a PR soon for NW, E, S, SW, etc and other 'compass directions' in the street address.  If anyone can think of any other common exceptions for street address please chime in.

Seems like we'd need to add a list of standard all-caps directionals
like N, S, E, W, NE, etc., similar to what's done for other
exceptions around here:
https://github.com/cividesk/com.cividesk.normalize/blob/master/CRM/Utils/Normalize.php#L90

**Comment by nganivet** [comment]
OK, perfect. Thanks.

**Comment by Stoob** [comment]
Hey Nicolas, how does this work now that the issues is closed?  Will it be merged into a new version?  When will release? Just wondering if I patch now, or wait a few days - this is new so I'm not sure how it works. thanks
